version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "metro"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vguxzz4gd7cc"
s3_prefix = "metro"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
